# Example configuration with debug logging enabled
# This file should be placed at /app/config/config.yaml

# Basic bot settings
interval: 60  # minutes between boost cycles
log_level: "DEBUG"  # Set to DEBUG to see detailed logging

# NEW: Debug decision logging
debug_decisions: true  # Enable detailed decision tracing
logfile_path: "/app/logs/hypebot_debug.log"  # Path to log file for persistent logging

# Instance subscriptions
subscribed_instances:
  mastodon.social:
    limit: 5
  chaos.social:
    limit: 3
  fosstodon.org:
    limit: 2

# Content filtering
require_media: true
skip_sensitive_without_cw: true
min_reblogs: 2
min_favourites: 5
languages_allowlist: ["en", "de"]

# Boost limits
daily_public_cap: 48
per_hour_public_cap: 1
max_boosts_per_run: 5
max_boosts_per_author_per_day: 1

# Hashtag scoring (optional)
hashtag_scores:
  python: 10
  mastodon: 5
  opensource: 3