# Refresh interval in minutes
interval: 60

# Text to add to the bot profile befor the list of subscribed servers
profile_prefix: "I am boosting trending posts from:"

# profile fields to fill in
fields:
  code: https://github.com/goingdark-social/hypebot
  operator: "YOUR HANDLE HERE"

# Define subscribed instances and
# their individual limit (top n trending posts)
# which is again limited by the API to max 20
subscribed_instances:
  chaos.social:
    limit: 5
  mastodon.social:
    limit: 5

# Posts originating from filtered instances will never be reposted.
# The filter checks for the instance of the original posting account, not the
# server that marked it as a popular post.
# This can be used to filter out abusive instances as well as protect small
# instances who could be overwhelmed with a repost to a significant amount of
# other instances
filtered_instances:
  - example.com

daily_public_cap: 48
per_hour_public_cap: 1
max_boosts_per_run: 5
max_boosts_per_author_per_day: 1
author_diversity_enforced: true
prefer_media: 1
require_media: true
skip_sensitive_without_cw: true
min_reblogs: 0
min_favourites: 0
languages_allowlist:
  - en
  - sv
state_path: "/app/secrets/state.json"
# Number of posts to remember for duplicate detection
seen_cache_size: 6000
hashtag_scores:
  python: 10
  rust: 5
