# Example configuration showcasing new scoring enhancements and fetch/boost limits

# Fetch larger candidate pools with controlled boost output
interval: 15  # Check every 15 minutes (new default)

# Age decay configuration - prevents boosting stale content
age_decay_enabled: true
age_decay_half_life_hours: 24.0  # Score halves every 24 hours

# Hashtag diversity - prevents multiple posts with same hashtag per run  
hashtag_diversity_enforced: true
max_boosts_per_hashtag_per_run: 1  # Only one post per hashtag per boost cycle

# Enhanced hashtag scoring with negative weights
hashtag_scores:
  # Positive weights boost preferred content
  python: 10
  programming: 8
  opensource: 5
  
  # Zero weights are neutral
  neutral: 0
  
  # Negative weights downrank or exclude content
  spam: -10
  offtopic: -5
  lowquality: -15

# Quality threshold - only boost posts meeting minimum score
min_score_threshold: 5  # Typical: low ~2, medium ~6, high ~13+

# Boost limits
daily_public_cap: 48
per_hour_public_cap: 6
max_boosts_per_run: 8  # Total across all instances
prefer_media: 0.5

# Instance configuration with separate fetch and boost limits
subscribed_instances:
  chaos.social:
    fetch_limit: 20  # Fetch 20 candidates from API
    boost_limit: 4   # Boost up to 4 best posts
  mastodon.social:  
    fetch_limit: 15  # Fetch 15 candidates
    boost_limit: 3   # Boost up to 3 best posts
  
  # Legacy format still works:
  # fosstodon.org:
  #   limit: 5  # Fetch and boost up to 5