name: Build and push Docker images to GHCR
on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push-ghcr-image:
    name: Build Docker image and push to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image (develop branch)
        if: ${{ github.ref_name == 'develop' }}
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ghcr.io/${{ github.repository_owner }}/hypebot:develop
          push: true

      - name: Build and push image (main branch)
        if: ${{ github.ref_name == 'main' }}
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ghcr.io/${{ github.repository_owner }}/hypebot:latest
          push: true

      - name: Image digest (develop)
        if: ${{ steps.build_and_push_develop.outcome == 'success' }}
        run: echo ${{ steps.build_and_push_develop.outputs.digest }}

      - name: Image digest (main)
        if: ${{ steps.build_and_push_main.outcome == 'success' }}
        run: echo ${{ steps.build_and_push_main.outputs.digest }}
