name: Build and push Docker images to GHCR
on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push-ghcr-image:
    name: Build Docker image and push to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ github.token }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build and push image (develop branch)
        if: ${{ github.ref_name == 'develop' }}
        id: build_and_push_develop
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/hypebot:develop
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      - name: Build and push image (main branch)
        if: ${{ github.ref_name == 'main' }}
        id: build_and_push_main
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/hypebot:v0.1.0
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      - name: Image digest (develop)
        if: ${{ steps.build_and_push_develop.outcome == 'success' }}
        run: echo ${{ steps.build_and_push_develop.outputs.digest }}

      - name: Image digest (main)
        if: ${{ steps.build_and_push_main.outcome == 'success' }}
        run: echo ${{ steps.build_and_push_main.outputs.digest }}
